### ISSUE TITLE
Crear imagen del UMl

### ISSUE THREAD

**Issue by yosbel-penate** [LachoCardenas44/GestionAlmacen.VisualParadigm#1]
Exportar el uml en formato jpg

**Comment by LachoCardenas44** [comment]
Hecho

**Comment by yosbel-penate** [comment]
Veo un uso indiscriminado de las relaciones fuertes. Una relación fuerte existe cuando la vida del objeto superior depende se la existencia de al menos un objeto inferior. Por tanto para establecer las relación puedo preguntar. Si desapareces, desaparece el objeto en el que estás. Por ejemplo el werhause desaparece si se borra el último appmanager 

En vuestra aplicación no hay internalagents? 

Las clases indeliverynote, outdeliverynote, delivery,order no se almacenan en ningún lado. 

La aplicación asumo que no es de celular o web. Y que sea de escritorio y real nada de simulaciones

**Comment by yosbel-penate** [comment]
Veo un uso indiscriminado de las relaciones fuertes. Una relación fuerte existe cuando la vida del objeto superior depende se la existencia de al menos un objeto inferior. Por tanto para establecer las relación puedo preguntar. Si desapareces, desaparece el objeto en el que estás. Por ejemplo el werhause desaparece si se borra el último appmanager 

En vuestra aplicación no hay internalagents? 

Las clases indeliverynote, outdeliverynote, delivery,order no se almacenan en ningún lado. 

La aplicación asumo que no es de celular o web. Y que sea de escritorio y real nada de simulaciones

**Comment by vmcalderingamez** [comment]
Hecho y Actualizado

**Comment by LachoCardenas44** [comment]
Asigné relaciones a las clases InDeliveryNote y OutDeliveryNote , ahora estas se almacenan en el almacén , como dos listas que contienen información acerca de los pedidos y envíos.
No percibo la existencia de un agente interno ya que la aplicación no contempla información alguna de los empleados del almacén , no tendrían utilidad en el código.
Respecto a la agregación fuerte , ya modifiqué algunas que verdaderamente no la tenían , tal como las clases StockRecord y QualityRecord con la clase Producto.

**Comment by yosbel-penate** [comment]
Puede que no exista una persona gestionando el almacen pero alguien en algun momento tomará ese rol. O el almacen se gestiona solo?

**Comment by LachoCardenas44** [comment]
Hay una persona que ha de encargarse de ingresar la información en la aplicación que estamos creando , el problema es como contemplar eso en el programa , tal vez creando una clase Usuario que mediante un Username y un Password pueda acceder solo él o ellos a gestionar la aplicación . Que opina usted de esa idea ?

**Comment by yosbel-penate** [comment]
A eso se le llama rol, el rol esta asociado a una serie de responsabilidades, y se le asigan a los usuarios cuando se ponen en el sistema, ejemplo pedro empezó a trabajar el va a atender la tienda y el almacen. Entonces en el crud de adicionar un usuario, se le asigna el rol de tendero y de almacenero. Luego pedro cuando se loguee en el sistema podra acceder a las funciones del administrador del almacen y a las funciones del tendero. Asi que el user tendrá varios roles. Pero no pretendo que sea tan completa la aplicación pero si que el diseño sea lo suficientemente flexible como para que en el futuro se puedan adicionar estas funcionalidades sin modificar el código existente.
